image: docker:latest

stages:
  - cleanup
  - test
  - deploy

cleanup:
  stage: cleanup
  image: docker:latest
  services:
    - name: docker:dind
  allow_failure: true
  script:
    - docker system prune -af
    - echo $CI_COMMIT_TAG
    - echo $CI_COMMIT_BRANCH


coverage_develop:
  stage: test
  image: docker/compose:latest
  services:
    - name: docker:dind
  allow_failure: true
  rules: 
   - if: '($CI_COMMIT_BRANCH == "develop") && $CI_COMMIT_TAG != null'
  script:
    - echo $GOOGLE_APPLICATION_CREDENTIALS_JSON > key.json
    - apk add bash
    - bash ./generate.env.sh develop
    - docker-compose down
    - docker-compose up --build test




deploy_develop:
  stage: deploy
  image: google/cloud-sdk
  services:
    - docker:dind
  rules: 
    - if: '($CI_COMMIT_BRANCH == "develop") && $CI_COMMIT_TAG != null'
  script:
    - echo $GCP_SERVICE_KEY_DEV > gcloud-service-key.json 
    - gcloud auth activate-service-account --key-file gcloud-service-key.json
    - gcloud config set project xskylab-development
    - gcloud builds submit . --config=cloudbuild.yaml --substitutions=TAG_NAME=$CI_COMMIT_TAG
