steps:
  - id: Build
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - "--no-cache"
      - "-t"
      - "$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
      - .
      - "-f"
      - Dockerfile

  - id: Push
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - "$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"

  - id: Apply Migrations
    name: gcr.io/google-appengine/exec-wrapper
    args:
      - "-i"
      - "$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
      - "-s"
      - "$PROJECT_ID:$_DEPLOY_REGION:$_DATABASE_INSTANCE_NAME"
      - "-e"
      - "SECRETS_NAME=$_SECRETS_NAME"
      - "--"
      - "python"
      - "manage.py"
      - "migrate"
      - "--settings"
      - "$_DJANGO_SETTINGS_NAME"

  - id: Collect static
    name: gcr.io/google-appengine/exec-wrapper
    args:
      - "-i"
      - "$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
      - "-s"
      - "$PROJECT_ID:$_DEPLOY_REGION:$_DATABASE_INSTANCE_NAME"
      - "-e"
      - "SECRETS_NAME=$_SECRETS_NAME"
      - "--"
      - "python"
      - "manage.py"
      - "collectstatic"
      - "--verbosity"
      - "2"
      - "--no-input"
      - "--settings"
      - "$_DJANGO_SETTINGS_NAME"

  - id: Deploy
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - "--platform=managed"
      - "--image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID
      - "--region=$_DEPLOY_REGION"
      - "--quiet"
    entrypoint: gcloud
images:
  - "$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _DATABASE_INSTANCE_NAME: agribusiness-agrocheck-ms-production-1
  _DEPLOY_REGION: us-central1
  _GCR_HOSTNAME: us.gcr.io
  _SERVICE_NAME: service-agribusiness-bndes
  _SECRETS_NAME: agribusiness-microservice-bndes
  _DJANGO_SETTINGS_NAME: skyviewer_api.settings.production
