steps:

  - id: Build
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - "--no-cache"
      - "-t"
      - "gcr.io/xskylab-development/hex360/$_SERVICE_NAME:$TAG_NAME"
      - .
      - "-f"
      - Dockerfile

  - id: Push
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - "gcr.io/xskylab-development/hex360/$_SERVICE_NAME:$TAG_NAME"

#  - id: Apply Migrations
#    name: gcr.io/google-appengine/exec-wrapper
#    args:
#      - "-i"
#      - "gcr.io/xskylab-development/hex360/$_SERVICE_NAME:$TAG_NAME"
#      - "-s"
#      - "$PROJECT_ID:$_DEPLOY_REGION:$_DATABASE_INSTANCE_NAME"
#      - "-e"
#      - "SECRETS_NAME=$_SECRETS_NAME"
#      - "--"
#      - "python"
#      - "manage.py"
#      - "migrate"
#      - "--settings"
#      - "$_DJANGO_SETTINGS_NAME"

#  - id: Collect static
#    name: gcr.io/google-appengine/exec-wrapper
#    args:
#      - "-i"
#      - "gcr.io/xskylab-development/hex360/$_SERVICE_NAME:$TAG_NAME"
#      - "-s"
#      - "$PROJECT_ID:$_DEPLOY_REGION:$_DATABASE_INSTANCE_NAME"
#      - "-e"
#      - "SECRETS_NAME=$_SECRETS_NAME"
#      - "--"
#      - "python"
#      - "manage.py"
#      - "collectstatic"
#      - "--verbosity"
#      - "2"
#      - "--no-input"
#      - "--settings"
#      - "$_DJANGO_SETTINGS_NAME"

  - id: Deploy
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - "--platform=managed"
      - "--image=gcr.io/xskylab-development/hex360/$_SERVICE_NAME:$TAG_NAME"
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID
      - "--region=$_DEPLOY_REGION"
      - "--quiet"
    entrypoint: gcloud
images:
  - "gcr.io/xskylab-development/hex360/$_SERVICE_NAME:$TAG_NAME"
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _DATABASE_INSTANCE_NAME: agribusiness-agrocheck-ms-production-1
  _DEPLOY_REGION: us-central1
  _GCR_HOSTNAME: us.gcr.io
  _SERVICE_NAME: service-agribusiness-bndes
  _SECRETS_NAME: agribusiness-microservice-bndes
  _DJANGO_SETTINGS_NAME: service_bndes_api.settings.production
